### ISSUE TITLE
updating home page

### ISSUE THREAD

**Issue by vkinnealey** [savvylee11/finalproject#12]
i really like the content on your site, but on second review i wonder if you might want to add more of an 'intro' to the home page so it doesn't jump right into the content? without you explaining the posts, its unclear what "James Introcaso: The World Builder" means (I obviously know from you presentation its a project you worked on, but I think prefacing that page with that information would be really helpful!)

**Comment by savvylee11** [comment]
That's a really good idea! Will definitely do that tonight. Thanks!
