### ISSUE TITLE
"About Me" section and resume 

### ISSUE THREAD

**Issue by jaclynglover** [savvylee11/finalproject#13]
I really like the layout of your site, Savannah. You've done a nice job of showcasing your work and portfolio as a writer AND web developer. Your new post template that looks like a notebook page is so cool and well done. A few ideas and suggestions for the future:

- You might consider moving your little "About Me" blurb from your footer and into your sidebar, so that it's more immediately visible to readers.
- You mentioned in your presentation that you might add a PDF viewer plugin so that you can upload your resume to your site. I think this would be a good addition.
- Your 404 page is amazing. No improvements needed there! 

Awesome job.

**Comment by savvylee11** [comment]
Thanks so much! I'm going to definitely add the PDF viewer and the sidebar idea is actually really good. Will consider doing that once I transition from a class project to a full time personal blog. Thanks again!
