### ISSUE TITLE
Mobile viewing 

### ISSUE THREAD

**Issue by tatyanaberdan** [savvylee11/finalproject#14]
I love the critic's notebook that you created - it looks super cool! 

The only thing I noticed and only piece of feedback I have is that it doesn't appear in the correct size on mobile: it's too big to fit on the screen. I don't know if there's an easy, code way to fix that since it's a pretty big image - you might consider [this plugin](https://wordpress.org/plugins/adaptive-images/), which helps you resize images for mobile. Otherwise I think the site looks great - congrats!

**Comment by savvylee11** [comment]
Great catch, Tatyana! Just downloaded the plugin... thanks so much!
