### ISSUE TITLE
Feedback!

### ISSUE THREAD

**Issue by mollykorroch** [savvylee11/finalproject#15]
I appreciate the black dimmer thing. Well done. Nice and subtly dramatic. Oooooh! And you did the custom template. Well done. Ha! And the post is about Britten. Ten points to Gryffindor. I’m not sure why, but some of the content seems a bit scrunched and like it’s floating. Perhaps a sidebar element would help offset that? I like that custom template, but the negative space around it doesn't seem to have any purpose. But! That’s totally a subjective opinion. You do you girl.

**Comment by savvylee11** [comment]
Hahaha thank you! The white space on the custom template was a headache. I wanted it gone, but apparently the 2017 theme has like layers on top of layers for pages and not stand alone pages... if that makes sense. So the notebook paper is technically spread out across its page, and there's another page behind it. Tried to toggle with it but it was something I had to let go. Silly wordpress.
