### ISSUE TITLE
Feedback:)

### ISSUE THREAD

**Issue by alliefoard** [savvylee11/finalproject#3]
Hey! 

I thought that your code was really well written. I am jealous of your shadow in your .css that you added to your navigation bar. I think that added a really cool visual element and was surprised at how easy the code was for it. (I might steal it later in life) I also thought that your custom post type with your background of the notebook was really creative. I remember us working on it in class and you thinking that you wouldn't be able to do it, and the code that you created looks like it was difficult, but I am glad that you didn't give up. I loved your 404 page, and thought that modification really showed that you thought outside of the box.

**Comment by savvylee11** [comment]
Thanks, Allie! I'm more than happy to share the shadow code :)
