### ISSUE TITLE
A Couple of Notes

### ISSUE THREAD

**Issue by xof88** [savvylee11/finalproject#4]
Hi Savannah! Really great work on your site! I have a couple notes for you to take or leave as you wish:)

1. On your homepage, consider changing your Posts header to instead be more descriptive of what is below, like Portfolio. 
2. Maybe move your footer with an image of you + text to your About Me page, and instead in the footer, add some buttons to your digital presence, aka. FB, IG, Twitter, blog, etc. 
3. I do like the idea of adding the PDF plugin to house your resume. That looked really nice on our classmates blog. 

Best of luck!
Jane

**Comment by savvylee11** [comment]
Thanks, Jane! I'm definitely adding the PDF viewer. And thanks for the other feedback, especially labeling the website a "portfolio." That will be super helpful down the road!
