### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by amaliaks** [savvylee11/finalproject#5]
First, I LOVE the fact that you coded an error 404 page. That is hilarious, unexpected, and adds even more flare to your page. Below are suggestions for your page:
-Center your name to the middle of the page and consider making the font larger
-Center the navigation to the middle and make it larger
-Left-align the picture and text of you and your fiancee to the left to align with the rest of the page and the text. Consider adding a line break between the posts and that section so readers know that it's different content. 
-Using a PDF viewer plugin to make your resume more prominent on the page because it rocks!

**Comment by savvylee11** [comment]
Thanks for the ideas! I'm definitely going to add the PDF viewer later on. I really like the look of it!
